//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class desglose_porcentaje
    {
        public int id_porcentaje { get; set; }
        public Nullable<int> id_desglose { get; set; }
        public Nullable<double> porcentaje { get; set; }
    }
}
