//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db : DbContext
    {
        public db()
            : base("name=db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora> bitacora { get; set; }
        public virtual DbSet<cantones> cantones { get; set; }
        public virtual DbSet<centros_educativos> centros_educativos { get; set; }
        public virtual DbSet<desglose> desglose { get; set; }
        public virtual DbSet<desglose_porcentaje> desglose_porcentaje { get; set; }
        public virtual DbSet<distritos> distritos { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<materias> materias { get; set; }
        public virtual DbSet<niveles> niveles { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<profesores> profesores { get; set; }
        public virtual DbSet<provincias> provincias { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_centro> tipo_centro { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
