//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_centro
    {
        public int id_tipo { get; set; }
        public string nombre_tipo { get; set; }
    }
}
